
platform :ios, '8.0'



# 用cocoapods导入OC框架到swift项目必须写该项

# user_frameworks!
# workspace 文件名

workspace 'WDProjects_dev.xcworkspace'

target 'WDProjects' do

pod 'Masonry', '~> 1.0.2'

end

target 'WDShare' do

platform :ios, '8.0'
project 'WDShare/WDShare.xcodeproj'
pod 'Masonry', '~> 1.0.2'

end

target 'WDUser' do

platform :ios, '8.0'
project 'WDUser/WDUser.xcodeproj'
pod 'Masonry', '~> 1.0.2'

end