# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WDEngineering' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WDEngineering

  target 'WDEngineeringTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WDEngineeringUITests' do
    # Pods for testing
  end

pod 'Masonry', '1.0.2'

end
